"""
MCP Server for Api-Architect Mode
Handles communication between the visual frontend canvas and IBM Bob LLM backend.
Provides endpoints for AI-powered code generation, refactoring, and chatbot interactions.
"""

import ast
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# MCP Server Application
app = FastAPI(
    title="IBM Bob Api-Architect MCP Server",
    description="Model Context Protocol server for frontend-backend AI integration",
    version="1.0.0",
)

# CORS configuration for frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Project paths
PROJECT_ROOT = Path(__file__).resolve().parent.parent
WORKSPACE_PATH = os.getenv("WORKSPACE_PATH", str(PROJECT_ROOT))


# ============================================================================
# Request/Response Models
# ============================================================================

class GenerateEndpointRequest(BaseModel):
    """Request to generate a new REST API endpoint."""
    method: str = Field(..., description="HTTP method (GET, POST, PUT, DELETE, PATCH)")
    path: str = Field(..., description="Endpoint path (e.g., /api/v1/users)")
    description: str = Field(..., description="Natural language description of endpoint logic")
    target_file: Optional[str] = Field(None, description="Target file path for the endpoint")
    include_tests: bool = Field(False, description="Whether to generate test cases")


class RefactorFunctionRequest(BaseModel):
    """Request to refactor an existing function using AI."""
    function_id: str = Field(..., description="Function identifier (file::function_name)")
    refactor_goal: str = Field(..., description="What to improve (e.g., 'optimize performance', 'add error handling')")
    preserve_signature: bool = Field(True, description="Keep function signature unchanged")
    workspace_path: Optional[str] = Field(
        None,
        description="Active workspace path used to resolve relative file paths",
    )


class AnalyzeCodeRequest(BaseModel):
    """Request to analyze code and provide insights."""
    file_path: Optional[str] = Field(None, description="Specific file to analyze")
    analysis_type: str = Field("general", description="Type of analysis: general, security, performance, quality")


class ChatCompletionRequest(BaseModel):
    """Request for chatbot interaction with context."""
    message: str = Field(..., description="User message/question")
    context: Optional[Dict[str, Any]] = Field(None, description="Additional context (selected node, file, etc.)")
    conversation_history: List[Dict[str, str]] = Field(default_factory=list, description="Previous messages")


class AIGenerationResponse(BaseModel):
    """Response from AI generation operations."""
    success: bool
    generated_code: Optional[str] = None
    file_path: Optional[str] = None
    explanation: Optional[str] = None
    suggestions: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)


class ChatCompletionResponse(BaseModel):
    """Response from chatbot."""
    message: str
    code_snippets: List[Dict[str, str]] = Field(default_factory=list)
    actions: List[Dict[str, Any]] = Field(default_factory=list)


# ============================================================================
# AI Integration Helpers
# ============================================================================

def _build_llm_prompt(task: str, context: Dict[str, Any]) -> str:
    """Build a structured prompt for IBM Granite LLM."""
    prompt_parts = [
        f"Task: {task}",
        "",
        "Context:",
    ]
    
    for key, value in context.items():
        if value:
            prompt_parts.append(f"- {key}: {value}")
    
    prompt_parts.extend([
        "",
        "Requirements:",
        "- Follow FastAPI best practices",
        "- Include proper type hints",
        "- Add error handling with HTTPException",
        "- Write clean, maintainable code",
        "- Include docstrings",
        "",
        "Generate the code:",
    ])
    
    return "\n".join(prompt_parts)


def _simulate_llm_generation(prompt: str, task_type: str) -> str:
    """
    Simulate LLM code generation.
    In production, this would call IBM Granite LLM API.
    """
    # This is a placeholder - in production, integrate with IBM Granite LLM
    if task_type == "endpoint":
        return """
@app.get("/api/v1/example")
async def get_example():
    \"\"\"
    Example endpoint generated by AI.
    Replace this with actual implementation.
    \"\"\"
    return {"message": "Generated endpoint", "status": "success"}
"""
    elif task_type == "refactor":
        return """
def refactored_function(param: str) -> Dict[str, Any]:
    \"\"\"
    Refactored function with improved structure.
    \"\"\"
    # Improved implementation
    result = process_data(param)
    return {"data": result, "status": "success"}
"""
    else:
        return "# Generated code placeholder"


def _analyze_code_quality(file_path: Path) -> Dict[str, Any]:
    """Analyze code quality and provide insights."""
    if not file_path.exists():
        return {"error": "File not found"}
    
    try:
        content = file_path.read_text(encoding="utf-8")
        lines = content.splitlines()
        
        return {
            "file": str(file_path),
            "lines_of_code": len(lines),
            "has_docstrings": '"""' in content or "'''" in content,
            "has_type_hints": "->" in content,
            "complexity": "medium",  # Placeholder
            "suggestions": [
                "Consider adding more comprehensive error handling",
                "Add unit tests for critical functions",
                "Document complex logic with inline comments",
            ],
        }
    except Exception as e:
        return {"error": str(e)}


def _file_contains_top_level_function(file_path: Path, function_name: str) -> bool:
    """Return True when a Python file defines the given top-level function."""
    try:
        source = file_path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(file_path))
    except Exception:
        return False

    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == function_name:
            return True
    return False


def _discover_source_file(source_path: Path, function_name: str) -> Optional[Path]:
    """
    Best-effort fallback discovery when the provided relative path cannot be resolved.
    Matches by relative suffix (e.g., `sample_api.py` or `services/user_service.py`)
    and prefers files that define the requested top-level function.
    """
    target_suffix = str(source_path).replace("\\", "/").lstrip("./")
    if not target_suffix:
        return None

    project_root = PROJECT_ROOT.resolve()
    candidates: List[Path] = []
    suffix_token = f"/{target_suffix}"

    for candidate in project_root.rglob("*.py"):
        rel = str(candidate.resolve().relative_to(project_root)).replace("\\", "/")
        if rel == target_suffix or rel.endswith(suffix_token):
            candidates.append(candidate.resolve())

    if not candidates:
        return None

    exact_fn_candidates = [
        path for path in candidates if _file_contains_top_level_function(path, function_name)
    ]
    pool = exact_fn_candidates or candidates
    pool = sorted(pool, key=lambda p: (len(str(p)), str(p)))
    return pool[0]


# ============================================================================
# MCP Endpoints
# ============================================================================

@app.get("/mcp/health")
async def health_check() -> Dict[str, str]:
    """Health check endpoint for MCP server."""
    return {
        "status": "healthy",
        "service": "api-architect-mcp",
        "version": "1.0.0",
    }


@app.post("/mcp/generate-endpoint", response_model=AIGenerationResponse)
async def generate_endpoint(request: GenerateEndpointRequest) -> AIGenerationResponse:
    """
    Generate a new REST API endpoint using AI.
    
    This endpoint receives a description from the frontend canvas and uses
    IBM Granite LLM to generate production-ready FastAPI endpoint code.
    """
    try:
        # Build context for LLM
        context = {
            "method": request.method,
            "path": request.path,
            "description": request.description,
            "target_file": request.target_file or "backend/main.py",
            "project_structure": "FastAPI with service layer pattern",
        }
        
        # Generate prompt
        prompt = _build_llm_prompt(
            f"Generate a FastAPI {request.method} endpoint for {request.path}",
            context,
        )
        
        # Call LLM (simulated for now)
        generated_code = _simulate_llm_generation(prompt, "endpoint")
        
        # Determine target file
        target_file = request.target_file or "backend/generated_endpoints.py"
        
        return AIGenerationResponse(
            success=True,
            generated_code=generated_code,
            file_path=target_file,
            explanation=f"Generated {request.method} endpoint for {request.path}",
            suggestions=[
                "Review the generated code before deploying",
                "Add authentication if needed",
                "Consider rate limiting for production",
            ],
            warnings=[],
        )
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Generation failed: {str(e)}")


@app.post("/mcp/refactor-function", response_model=AIGenerationResponse)
async def refactor_function(request: RefactorFunctionRequest) -> AIGenerationResponse:
    """
    Refactor an existing function using AI.
    
    Analyzes the current function and applies AI-powered refactoring
    based on the specified goal (performance, readability, error handling, etc.).
    """
    try:
        # Parse function_id
        if "::" not in request.function_id:
            raise HTTPException(status_code=400, detail="Invalid function_id format")
        
        file_path, function_name = request.function_id.rsplit("::", 1)
        source_path = Path(file_path)
        attempted_paths: List[str] = []

        workspace_root = Path(request.workspace_path).resolve() if request.workspace_path else Path(WORKSPACE_PATH).resolve()
        if source_path.is_absolute():
            full_path = source_path.resolve()
        else:
            full_path = (workspace_root / source_path).resolve()
        attempted_paths.append(str(full_path))

        if not full_path.exists():
            # Fallback to MCP default workspace in case frontend did not provide active workspace.
            fallback_root = Path(WORKSPACE_PATH).resolve()
            fallback_path = source_path.resolve() if source_path.is_absolute() else (fallback_root / source_path).resolve()
            attempted_paths.append(str(fallback_path))
            if fallback_path.exists():
                full_path = fallback_path
            else:
                discovered_path = None if source_path.is_absolute() else _discover_source_file(source_path, function_name)
                if discovered_path and discovered_path.exists():
                    full_path = discovered_path
                    attempted_paths.append(str(discovered_path))
                else:
                    raise HTTPException(
                        status_code=404,
                        detail=(
                            f"Source file not found: {file_path}. "
                            f"workspace_path={request.workspace_path or WORKSPACE_PATH}. "
                            f"attempted={attempted_paths}"
                        ),
                    )
        
        # Read current function code
        source_code = full_path.read_text(encoding="utf-8")
        
        # Build context for LLM
        context = {
            "function_name": function_name,
            "file": file_path,
            "refactor_goal": request.refactor_goal,
            "preserve_signature": request.preserve_signature,
            "current_code": source_code[:500],  # First 500 chars for context
        }
        
        # Generate prompt
        prompt = _build_llm_prompt(
            f"Refactor function '{function_name}' to {request.refactor_goal}",
            context,
        )
        
        # Call LLM (simulated for now)
        refactored_code = _simulate_llm_generation(prompt, "refactor")
        
        return AIGenerationResponse(
            success=True,
            generated_code=refactored_code,
            file_path=file_path,
            explanation=f"Refactored {function_name} to {request.refactor_goal}",
            suggestions=[
                "Test the refactored function thoroughly",
                "Compare performance with original implementation",
                "Update related documentation",
            ],
            warnings=[],
        )
    
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Refactoring failed: {str(e)}")


@app.post("/mcp/analyze-code")
async def analyze_code(request: AnalyzeCodeRequest) -> Dict[str, Any]:
    """
    Analyze code and provide insights.
    
    Performs static analysis and provides recommendations for improvements,
    security issues, performance optimizations, and code quality.
    """
    try:
        if request.file_path:
            # Analyze specific file
            file_path = Path(WORKSPACE_PATH) / request.file_path
            analysis = _analyze_code_quality(file_path)
        else:
            # Analyze entire backend directory
            backend_path = Path(WORKSPACE_PATH) / "backend"
            python_files = list(backend_path.glob("*.py"))
            
            analysis = {
                "total_files": len(python_files),
                "files": [str(f.relative_to(WORKSPACE_PATH)) for f in python_files],
                "summary": "Backend codebase analysis",
            }
        
        return {
            "status": "success",
            "analysis_type": request.analysis_type,
            "results": analysis,
        }
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Analysis failed: {str(e)}")


@app.post("/mcp/chat-completion", response_model=ChatCompletionResponse)
async def chat_completion(request: ChatCompletionRequest) -> ChatCompletionResponse:
    """
    Handle chatbot interactions with context awareness.
    
    Provides an AI assistant that can answer questions about the codebase,
    suggest improvements, and help with architectural decisions.
    """
    try:
        # Build context from conversation history
        context_parts = []
        
        if request.context:
            context_parts.append("Current Context:")
            for key, value in request.context.items():
                context_parts.append(f"- {key}: {value}")
        
        if request.conversation_history:
            context_parts.append("\nConversation History:")
            for msg in request.conversation_history[-3:]:  # Last 3 messages
                role = msg.get("role", "user")
                content = msg.get("content", "")
                context_parts.append(f"{role}: {content}")
        
        context_parts.append(f"\nUser: {request.message}")
        
        # Simulate AI response (in production, use IBM Granite LLM)
        if "endpoint" in request.message.lower():
            response_message = """I can help you create a new REST API endpoint! Here's what I need:

1. HTTP method (GET, POST, PUT, DELETE)
2. Endpoint path (e.g., /api/v1/users)
3. Description of what it should do

Would you like me to generate an endpoint for you?"""
            
            code_snippets = [{
                "language": "python",
                "code": """@app.get("/api/v1/example")
async def get_example():
    return {"message": "Hello World"}""",
            }]
            
            actions = [{
                "type": "generate_endpoint",
                "label": "Generate Endpoint",
                "description": "Create a new REST API endpoint",
            }]
        
        elif "refactor" in request.message.lower():
            response_message = """I can help refactor your functions! I can improve:

- Performance optimization
- Error handling
- Code readability
- Type safety
- Documentation

Select a function node and tell me what you'd like to improve."""
            
            code_snippets = []
            actions = [{
                "type": "refactor_function",
                "label": "Refactor Function",
                "description": "Improve existing function code",
            }]
        
        else:
            response_message = f"""I'm your Api-Architect assistant! I can help with:

🏗️ **Generate Endpoints**: Create new REST API endpoints from descriptions
🔧 **Refactor Code**: Improve existing functions with AI
📊 **Analyze Code**: Review code quality and suggest improvements
💬 **Answer Questions**: Help with FastAPI, Python, and architecture decisions

What would you like to work on?"""
            
            code_snippets = []
            actions = []
        
        return ChatCompletionResponse(
            message=response_message,
            code_snippets=code_snippets,
            actions=actions,
        )
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Chat completion failed: {str(e)}")


# ============================================================================
# Integration with existing backend
# ============================================================================

@app.post("/mcp/create-intent")
async def create_intent(payload: Dict[str, Any]) -> Dict[str, str]:
    """
    Create an intent file for IBM Bob to process.
    Integrates with the existing backend's intent system.
    """
    try:
        workspace_path = Path(WORKSPACE_PATH)
        bob_dir = workspace_path / ".bob"
        intent_file = bob_dir / "mcp_intent.json"
        
        # Ensure .bob directory exists
        bob_dir.mkdir(exist_ok=True)
        
        # Create intent payload
        intent_data = {
            "source": "mcp-server",
            "timestamp": "2024-01-01T00:00:00Z",  # In production, use actual timestamp
            "task": payload.get("task", "Process MCP request"),
            **payload,
        }
        
        # Write intent file
        with open(intent_file, "w", encoding="utf-8") as f:
            json.dump(intent_data, f, indent=2)
        
        return {
            "status": "success",
            "message": "Intent created for IBM Bob processing",
            "intent_file": str(intent_file),
        }
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Intent creation failed: {str(e)}")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("mcp_server:app", host="127.0.0.1", port=5001, reload=True)

# Made with Bob
